<a href="https://colab.research.google.com/github/MohitNath007/Raksha_Pipes_Analysis/blob/main/Mohit_Nath_Raksha_pipes_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
!pip install faker

from faker import Faker
import random

fake = Faker()

# 1. Products table with product_price column
product_names = [
    ("PVC Pipe", 10.99), ("CPVC Pipe", 12.99), ("uPVC Pipe", 15.99), ("HDPE Pipe", 18.99),
    ("PVC Fittings", 5.99), ("CPVC Fittings", 7.99), ("uPVC Fittings", 9.99), ("HDPE Fittings", 11.99),
    ("PVC Valve", 8.99), ("CPVC Valve", 10.99), ("uPVC Valve", 12.99), ("HDPE Valve", 14.99),
    ("PVC Elbow", 4.99), ("CPVC Elbow", 6.99), ("uPVC Elbow", 8.99), ("HDPE Elbow", 10.99)
]

products = [(idx + 1, product_name, price) for idx, (product_name, price) in enumerate(product_names)]

# 2. Customers table
countries = ["Singapore", "Middle East", "Europe", "India", "Russia", "Australia"]

# Define states before the loop where it's used
states_by_country = {
    "Singapore": ["Central Region", "East Region", "North Region", "North-East Region", "West Region"],
    "Middle East": ["Dubai", "Abu Dhabi", "Doha", "Riyadh", "Muscat"],
    "Europe": ["London", "Paris", "Berlin", "Rome", "Madrid"],
    "India": ["Delhi", "Mumbai", "Bangalore", "Chennai", "Kolkata"],
    "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan"],
    "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"]
}

states = [(idx + 1, state, country_id + 1) for country_id, country in enumerate(countries) for idx, state in enumerate(states_by_country.get(country))]

customers = []
for idx in range(700):
    country = random.choice(countries)
    state = random.choice(states_by_country[country])  # Randomly select a state based on the chosen country
    customers.append((idx + 1, fake.name(), fake.street_address(), fake.phone_number(), state, country))

# 3. Sales table
sales = [(idx + 1, random.choice(products)[0], random.choice(customers)[0], random.randint(1, 10), fake.date_between(start_date='-1y', end_date='today')) for idx in range(700)]

# 4. Categories table
categories = [(idx + 1, category) for idx, category in enumerate(["agriculture", "plumbing", "industrial", "bath", "water_tank"])]

# 5. Orders table
orders = [(idx + 1, random.choice(customers)[0], random.choice(products)[0], fake.date_between(start_date='-1y', end_date='today'), fake.date_between(start_date='-1y', end_date='today')) for idx in range(700)]

# 6. Payments table
payments = [(idx + 1, random.choice(orders)[0], random.uniform(10, 1000), fake.date_between(start_date='-1y', end_date='today')) for idx in range(300)]

# 7. Suppliers table
suppliers = [(idx + 1, fake.company(), random.choice(countries)) for idx in range(100)]

# 8. Distributors table
distributors = [(idx + 1, fake.company(), fake.street_address(), fake.phone_number(), random.choice(countries)) for idx in range(50)]

# Print the generated data for each table
print("Products:")
for product in products:
    print(product)

print("\nCustomers:")
for customer in customers:
    print(customer)

print("\nSales:")
for sale in sales:
    print(sale)

print("\nCategories:")
for category in categories:
    print(category)

print("\nOrders:")
for order in orders:
    print(order)

print("\nPayments:")
for payment in payments:
    print(payment)

print("\nSuppliers:")
for supplier in suppliers:
    print(supplier)

print("\nDistributors:")
for distributor in distributors:
    print(distributor)

Requirement already satisfied: faker in /usr/local/lib/python3.10/dist-packages (25.2.0)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Products:
(1, 'PVC Pipe', 10.99)
(2, 'CPVC Pipe', 12.99)
(3, 'uPVC Pipe', 15.99)
(4, 'HDPE Pipe', 18.99)
(5, 'PVC Fittings', 5.99)
(6, 'CPVC Fittings', 7.99)
(7, 'uPVC Fittings', 9.99)
(8, 'HDPE Fittings', 11.99)
(9, 'PVC Valve', 8.99)
(10, 'CPVC Valve', 10.99)
(11, 'uPVC Valve', 12.99)
(12, 'HDPE Valve', 14.99)
(13, 'PVC Elbow', 4.99)
(14, 'CPVC Elbow', 6.99)
(15, 'uPVC Elbow', 8.99)
(16, 'HDPE Elbow', 10.99)

Customers:
(1, 'Mary Rodriguez', '162 Miller Summit', '001-997-892-5278x78569', 'Chennai', 'India')
(2, 'Mr. James Porter', '71068 Emily Roads Apt. 091', '+1-762-812-8087x36727', 'Berlin', 'Europe')
(3, 'Rachel Meyer', '9168 Oscar Manors Apt. 274', '449.908.8201x45046', 'Kolkata', 'India')
(4, 'Taylor Williams', '600 Richard Wall', '7367468066', 'North Region', 'Singapore')
(5, 'Elizabeth Brown', '34252 Davis Forest Apt. 832', '301-736-0524', 'West Region', 'Singapore')
(6, 'Aimee Liu', '0580 Sara Rapids Apt. 048', '(706)279-3029', 'Dubai', 'Middle East')
(7, 'Kathleen Sanchez', '6026 Taylor Groves', '929.384.3370', 'Abu Dhabi', 'Middle East')
(8, 'Brian Warner', '58279 Nathan Cove Suite 298', '(782)789-2551x6053', 'Brisbane', 'Australia')
(9, 'Megan Long', '37851 Lisa Well Apt. 574', '4989928471', 'Central Region', 'Singapore')
(10, 'Christian Lee', '2887 Pamela Isle Suite 133', '+1-643-888-3736', 'Saint Petersburg', 'Russia')
(11, 'Todd Lowery', '590 Serrano Spur', '(223)544-0138', 'Riyadh', 'Middle East')
(12, 'Veronica Silva', '822 Tiffany Ferry Apt. 660', '7935839787', 'North Region', 'Singapore')
(13, 'Lori Richard', '096 Arnold Loop Apt. 061', '+1-765-927-8612x23489', 'Yekaterinburg', 'Russia')
(14, 'Nicole Brown', '1129 Richard Flat', '+1-547-993-2032x619', 'London', 'Europe')
(15, 'Tamara Nunez', '71469 Colon Shores', '837-538-3466', 'Muscat', 'Middle East')
(16, 'James Perry', '945 Daniel Inlet', '001-683-851-3227x4422', 'Sydney', 'Australia')
(17, 'Felicia Ward', '5635 Bowman Motorway', '771-632-8474x7816', 'North-East Region', 'Singapore')
(18, 'Mrs. Anne Thompson DDS', '049 Rubio Mill', '+1-337-847-3631x98350', 'Delhi', 'India')
(19, 'John Sanchez', '109 Gould Ford Suite 498', '001-255-463-3111x08696', 'North-East Region', 'Singapore')
(20, 'Gregory Mcpherson', '0266 Christine Mountain Apt. 129', '499.681.1542', 'Chennai', 'India')
(21, 'Jennifer Jackson', '30261 Karen Spring Suite 312', '704.908.5633', 'Riyadh', 'Middle East')
(22, 'Randall Williams', '697 Kim Shores', '320.620.4042', 'Moscow', 'Russia')
(23, 'Shannon Barker', '3061 Cory Brooks Apt. 233', '757.635.5043x52974', 'East Region', 'Singapore')
(24, 'Jason Cooper', '905 Ashley Gardens Apt. 284', '396-981-3113', 'Paris', 'Europe')
(25, 'Seth Medina', '181 Gonzalez Village', '250.714.1819x37120', 'Abu Dhabi', 'Middle East')
(26, 'Erica Brown', '31553 Adams Walk Apt. 792', '877.749.1712x6122', 'Doha', 'Middle East')
(27, 'Edward Todd', '17849 Adam Well Apt. 525', '235-877-7049', 'Chennai', 'India')
(28, 'Wesley Melton', '1920 Harper Mount', '848-340-5587x6874', 'Madrid', 'Europe')
(29, 'Mr. Michael Hall', '72401 Frank Ferry Apt. 615', '343.877.4171', 'East Region', 'Singapore')
(30, 'James Edwards', '123 Johnson Wall', '4508815567', 'Rome', 'Europe')
(31, 'Jeffrey Peck', '662 Nicholas Junctions Suite 740', '631.626.7475x812', 'Doha', 'Middle East')
(32, 'Dwayne Allen', '37079 April Underpass', '001-262-500-0010x46080', 'Paris', 'Europe')
(33, 'Eric Frey', '0477 Mcbride Walk', '(267)398-6951x789', 'Chennai', 'India')
(34, 'Ashley Fernandez', '889 Brian Run Suite 022', '927-872-5475x04386', 'East Region', 'Singapore')
(35, 'Jill Williams', '83760 Martinez Avenue Suite 491', '695-519-5522', 'Adelaide', 'Australia')
(36, 'James Moses', '6860 John Village', '622-675-7311x449', 'Kolkata', 'India')
(37, 'Eric Franklin', '104 Chapman Port Suite 899', '940.413.7695x8369', 'East Region', 'Singapore')
(38, 'Nicole Bennett', '62534 Parker Union Apt. 470', '+1-914-535-9195x304', 'Berlin', 'Europe')
(39, 'Gregory Brown', '65126 Daniel Lodge', '(453)277-0798x444', 'Kolkata', 'India')
(40, 'Sherri Perez', '450 Miller Path', '+1-832-347-1838x45497', 'North Region', 'Singapore')
(41, 'Rachel Olsen', '05972 Michelle Station', '001-969-433-9677', 'Kazan', 'Russia')
(42, 'Timothy Gray', '439 Chad Squares', '001-416-651-2807x90246', 'London', 'Europe')
(43, 'John Wilson', '643 Lewis Lights Suite 590', '+1-620-397-5895', 'Kolkata', 'India')
(44, 'James Harris', '700 Jeffery Square Suite 540', '362-244-1961', 'North-East Region', 'Singapore')
(45, 'Tyler Simmons', '75949 Wesley Hollow', '+1-519-346-1094x63611', 'Moscow', 'Russia')
(46, 'Justin Murphy', '08603 Simpson Island Apt. 640', '384.897.5652', 'Sydney', 'Australia')
(47, 'Cheryl Villanueva', '453 Marisa Trail Apt. 889', '(251)505-5336x79548', 'Madrid', 'Europe')
(48, 'Stacey Jensen', '6149 Lyons Loop', '001-989-773-4456x002', 'Brisbane', 'Australia')
(49, 'Donna Bowen', '40705 Gonzalez Station', '001-411-359-9606x836', 'West Region', 'Singapore')
(50, 'Susan Doyle', '03558 Johnson Crest', '+1-930-720-1314x735', 'East Region', 'Singapore')
(51, 'Oscar Rogers', '0950 Avila Turnpike Apt. 625', '9778657449', 'Doha', 'Middle East')
(52, 'Adam Cook', '8239 David Extension', '(816)611-8339', 'Central Region', 'Singapore')
(53, 'Charles Long', '485 Joseph Brooks', '771.386.5100', 'Paris', 'Europe')
(54, 'Susan Rosales', '918 Johnson Mount', '+1-826-638-7401x5841', 'Delhi', 'India')
(55, 'Paul Brown', '489 Samantha Pass Apt. 220', '(729)344-5340', 'Perth', 'Australia')
(56, 'Vanessa Pennington', '062 Jordan Row Apt. 196', '844-700-4141x14488', 'Muscat', 'Middle East')
(57, 'Jessica Leon', '28401 Taylor Falls Apt. 505', '269.211.7161x058', 'East Region', 'Singapore')
(58, 'Michelle Hampton', '207 Harold Lakes Suite 531', '405.316.6806', 'Adelaide', 'Australia')
(59, 'James Mejia', '60160 Kelsey Mall', '684-752-0781x669', 'Rome', 'Europe')
(60, 'Colleen Nunez', '78425 Cynthia Burgs', '8698826242', 'Yekaterinburg', 'Russia')
(61, 'Allison Price', '16839 Christopher Villages', '944.988.2947x5303', 'West Region', 'Singapore')
(62, 'Jason Chapman', '636 Davidson Overpass Apt. 392', '733.861.9924x753', 'Yekaterinburg', 'Russia')
(63, 'Karen Hull', '79748 Natalie Points', '+1-777-317-5539x606', 'Kolkata', 'India')
(64, 'Richard Garcia', '70919 Miranda Pike', '001-389-785-7330x21823', 'Mumbai', 'India')
(65, 'Teresa Graham', '205 Perez View Suite 916', '899-631-2339', 'Rome', 'Europe')
(66, 'Daniel Mueller', '3601 Shields Row', '742.534.3387', 'Berlin', 'Europe')
(67, 'Melissa Herring', '6762 Bernard Garden', '942-898-2288x4995', 'North Region', 'Singapore')
(68, 'Kim Mcknight', '3209 Diana Turnpike', '393-227-5476x975', 'Yekaterinburg', 'Russia')
(69, 'Laura Garza', '5305 Jeremy Loaf', '+1-642-281-8205x89304', 'North-East Region', 'Singapore')
(70, 'Herbert Miller', '8664 Brittany Expressway Apt. 947', '+1-294-251-4898x266', 'Dubai', 'Middle East')
(71, 'Cynthia Khan', '29013 Ronnie Pines Suite 290', '001-674-226-6365', 'East Region', 'Singapore')
(72, 'Susan Bullock DDS', '363 Laura Villages', '614.879.9754x32863', 'Kazan', 'Russia')
(73, 'Eric Miller', '56036 Fox Hill Apt. 719', '001-866-974-4908x1804', 'Berlin', 'Europe')
(74, 'George Manning', '300 Patrick Extensions', '001-839-402-6532x3690', 'Sydney', 'Australia')
(75, 'Cody Morgan', '74671 Dennis Island', '(815)651-5248x41385', 'Moscow', 'Russia')
(76, 'Sara Duncan', '738 Carr Street Apt. 730', '(387)966-6015', 'Muscat', 'Middle East')
(77, 'Douglas Mullins', '615 Henry Greens', '600-261-1369x86695', 'Rome', 'Europe')
(78, 'Lisa Richards', '1412 Joshua Junction Suite 688', '253-538-4715x5352', 'Novosibirsk', 'Russia')
(79, 'Derrick Gomez', '195 Kristy Coves Apt. 659', '739-246-3054', 'Mumbai', 'India')
(80, 'George Tran', '391 Darren Row', '001-489-835-0227x8128', 'Sydney', 'Australia')
(81, 'Patty Aguilar', '74701 Schultz Circle Apt. 725', '001-694-351-4092x02039', 'Doha', 'Middle East')
(82, 'Alexis Evans', '044 Johnson Street Suite 824', '+1-304-921-4847x53396', 'Abu Dhabi', 'Middle East')
(83, 'Kevin Shaw', '70456 Charles Branch Suite 780', '921-687-2433', 'Madrid', 'Europe')
(84, 'Mr. John Abbott', '17518 Robert Meadow', '(841)235-2809', 'Moscow', 'Russia')
(85, 'Lindsey Walker', '57230 Garrison Lakes', '267.893.5960x383', 'London', 'Europe')
(86, 'Kathryn Martin', '7114 Amy Square', '(349)664-2952x758', 'Riyadh', 'Middle East')
(87, 'Ronnie Vargas', '2128 Elizabeth Extension', '8687640828', 'Chennai', 'India')
(88, 'Rebecca Robinson', '21949 Odom Lock', '+1-817-335-0155x385', 'Perth', 'Australia')
(89, 'Regina Spence', '58407 Simon Parks Apt. 325', '(876)645-1371x4854', 'Sydney', 'Australia')
(90, 'Elizabeth Morales', '067 Jones Drive', '+1-501-515-6594x85039', 'Sydney', 'Australia')
(91, 'Kevin Jones', '86933 Larson Ways', '001-588-744-1663', 'Melbourne', 'Australia')
(92, 'Anthony Taylor', '83496 Nicole Island Apt. 485', '870-288-9629x396', 'Madrid', 'Europe')
(93, 'Sharon Osborne', '1108 Mclaughlin Mountains', '001-307-564-0808x9075', 'Delhi', 'India')
(94, 'Gloria Holt', '599 Roberta Crescent Apt. 806', '3999007880', 'Melbourne', 'Australia')
(95, 'Kyle Ray', '79868 Brian Prairie Apt. 987', '802.667.8779', 'Melbourne', 'Australia')
(96, 'Rebecca Long', '89286 Harmon Manor Suite 418', '001-547-353-9649x92133', 'Berlin', 'Europe')
(97, 'Kaylee Allen', '61403 Moore Forges', '853-886-9645x9710', 'Brisbane', 'Australia')
(98, 'Wanda Mitchell', '53144 Obrien Prairie Apt. 970', '+1-711-967-7875', 'West Region', 'Singapore')
(99, 'Nicole Pham', '941 Justin Tunnel Suite 734', '001-287-656-2067x998', 'West Region', 'Singapore')
(100, 'Jacob Steele', '45849 Jessica Crossing Apt. 133', '820.371.0742', 'North Region', 'Singapore')
(101, 'Monica Miller', '584 Cathy Pine', '001-240-929-2037x35292', 'Bangalore', 'India')
(102, 'Brandon Williams', '629 Ryan Mountain Apt. 778', '001-413-935-2295x23425', 'Saint Petersburg', 'Russia')
(103, 'Ryan Garcia', '27762 Kimberly Valley', '(476)506-1020x6402', 'Riyadh', 'Middle East')
(104, 'Martin Mccoy', '0161 Michael Prairie', '768.870.8127', 'North-East Region', 'Singapore')
(105, 'Austin Powers', '4670 Thomas Cliffs Suite 506', '001-863-204-9263x51373', 'Dubai', 'Middle East')
(106, 'Michael Logan', '743 Mark Inlet Suite 148', '(955)577-4472', 'Bangalore', 'India')
(107, 'Brett Oneal', '617 Cassidy Falls', '657-518-9161x467', 'North-East Region', 'Singapore')
(108, 'Mrs. Vanessa Boyer', '111 Amy Walks Suite 073', '920-774-1727', 'London', 'Europe')
(109, 'Dennis Lee', '106 Nancy Landing', '370.805.2664', 'North Region', 'Singapore')
(110, 'Steven Moore', '186 Tracy Lane', '+1-462-638-9150x659', 'Mumbai', 'India')
(111, 'Rhonda Manning', '175 Eric Valleys', '348.318.0605', 'Paris', 'Europe')
(112, 'Brent Villanueva', '74416 James Flats Apt. 324', '001-922-973-0271x0855', 'East Region', 'Singapore')
(113, 'Joanne Smith', '010 Amber Pike Apt. 586', '6325508909', 'Delhi', 'India')
(114, 'Timothy Becker', '8788 Austin Station Apt. 713', '001-693-380-4598x72001', 'Doha', 'Middle East')
(115, 'Beverly Thompson', '354 Burns Track', '767-288-0906x862', 'Adelaide', 'Australia')
(116, 'Sarah Grimes', '26375 Kennedy Camp', '+1-903-341-3543x233', 'Riyadh', 'Middle East')
(117, 'Jennifer Bell', '835 King Cliffs Suite 694', '252.989.5811x559', 'North Region', 'Singapore')
(118, 'Benjamin Short', '17474 Gary Divide Apt. 837', '4185363755', 'Central Region', 'Singapore')
(119, 'Amanda Taylor', '76379 Patel Island', '(596)629-0319x20513', 'Muscat', 'Middle East')
(120, 'Jaclyn James', '34164 Denise Harbors Suite 874', '(226)659-3403', 'Novosibirsk', 'Russia')
(121, 'Lisa Nichols', '4726 Gabriel Hollow', '001-783-318-0979x090', 'Mumbai', 'India')
(122, 'Kathleen Nelson', '42107 Chad Roads', '8229585440', 'Kolkata', 'India')
(123, 'Brian Collins', '176 Ashley Pike', '001-874-455-0452x2883', 'Bangalore', 'India')
(124, 'Dr. Sarah Chapman DVM', '759 Williams Isle', '(964)336-3913', 'Adelaide', 'Australia')
(125, 'Jennifer Martin', '5162 Maria Mill Apt. 324', '264-231-5924x6906', 'Bangalore', 'India')
(126, 'Morgan Brown', '338 Sarah Crossroad', '001-642-954-3360x78167', 'Central Region', 'Singapore')
(127, 'Molly Cisneros', '0989 Lozano Drives', '730.747.0123x55860', 'North-East Region', 'Singapore')
(128, 'Sherry Garcia', '040 Mills Neck Suite 462', '001-928-822-6351x9327', 'Bangalore', 'India')
(129, 'Carla Estrada', '3098 Cristina Forks', '+1-856-916-2274x196', 'Yekaterinburg', 'Russia')
(130, 'Melanie Holland', '490 Hernandez Oval Suite 218', '(797)561-8533x779', 'Sydney', 'Australia')
(131, 'Danielle White', '54031 Sabrina Route Apt. 659', '(418)307-5664x90473', 'North-East Region', 'Singapore')
(132, 'Timothy Rosario', '0614 Sheri Centers', '(943)374-0921x63878', 'Madrid', 'Europe')
(133, 'Eugene Zamora', '42811 Vargas Groves', '+1-635-469-1521x262', 'Abu Dhabi', 'Middle East')
(134, 'Blake Brooks', '30760 Erika Parkways', '001-491-472-1142x69782', 'Central Region', 'Singapore')
(135, 'Christian Tapia', '342 Collier Overpass', '387.564.8386x29252', 'Madrid', 'Europe')
(136, 'Richard Johnson', '4672 Burnett Spring Suite 027', '(560)544-8725x54311', 'Chennai', 'India')
(137, 'Oscar Jones', '9798 Martin Shore Suite 576', '251.259.8189x29907', 'Central Region', 'Singapore')
(138, 'Troy Duran', '126 Kevin Circles Apt. 075', '001-686-844-5110x6526', 'Central Region', 'Singapore')
(139, 'William Floyd', '43077 Robertson Via Suite 383', '(633)230-7824x397', 'Sydney', 'Australia')
(140, 'Steve Underwood', '048 Laurie Point', '+1-901-790-6104', 'Perth', 'Australia')
(141, 'Joseph Sanders', '32346 Julia Lake Apt. 800', '861-630-7013', 'Delhi', 'India')
(142, 'Bobby Wilcox', '45682 Smith Squares Apt. 031', '864-321-8819x6286', 'London', 'Europe')
(143, 'Angel Henson', '296 Garcia Parks', '(942)258-2525', 'Dubai', 'Middle East')
(144, 'Stanley Hobbs', '629 Holmes Road Apt. 349', '312.816.2233x907', 'Riyadh', 'Middle East')
(145, 'Jessica Martinez', '962 Ramos Lights Suite 394', '882.626.3758', 'Mumbai', 'India')
(146, 'Matthew Hernandez', '189 Bryan Unions', '(945)396-8704x78973', 'Perth', 'Australia')
(147, 'Ann Robbins', '2641 Monica Locks Suite 800', '489.339.1086x1623', 'North Region', 'Singapore')
(148, 'Mark Edwards', '6684 Joseph Squares', '(545)561-4682x8898', 'Paris', 'Europe')
(149, 'Shawn Lam', '55056 Kaitlyn Tunnel', '001-945-520-7397x03146', 'Brisbane', 'Australia')
(150, 'Mark Rice', '9203 Phillip Light Apt. 982', '966-483-4963', 'Delhi', 'India')
(151, 'Michelle Smith', '46813 Kathleen Stream', '001-562-402-8313x0673', 'North Region', 'Singapore')
(152, 'William Garcia', '41013 Amanda Heights Suite 002', '353.875.4251', 'Moscow', 'Russia')
(153, 'Brittany Kemp', '54343 Green Mall Suite 184', '+1-963-659-3054x54160', 'Mumbai', 'India')
(154, 'Jennifer Owens', '7139 James Creek', '583-449-7140', 'Sydney', 'Australia')
(155, 'Mark Roberts', '45814 Dickerson Rest', '814-364-8523', 'Melbourne', 'Australia')
(156, 'Samantha Johnston', '93928 Parks Locks', '001-754-622-6314x28717', 'Perth', 'Australia')
(157, 'Norma Knight', '40172 Williams Ranch', '(356)784-8712', 'East Region', 'Singapore')
(158, 'Beth Williamson', '51239 Michael Village Suite 564', '(591)822-0677x4045', 'Berlin', 'Europe')
(159, 'Kevin Haney', '5376 Samantha Forks', '001-455-634-1462', 'Sydney', 'Australia')
(160, 'Michael Morton', '7810 Cynthia Fort', '7959808537', 'Abu Dhabi', 'Middle East')
(161, 'Drew Sheppard', '17976 Larsen Roads Apt. 770', '238-542-2039x718', 'Bangalore', 'India')
(162, 'Thomas Rivera', '1469 Stephanie Meadow', '001-348-865-9850x86251', 'Adelaide', 'Australia')
(163, 'Jesse Jordan', '495 Martinez Springs', '(847)464-6878x764', 'Central Region', 'Singapore')
(164, 'Laurie Navarro', '2969 Webb Meadows', '919-751-0349x8566', 'Paris', 'Europe')
(165, 'Tim Hoffman', '48337 Edward Unions Apt. 568', '233-627-9138', 'Moscow', 'Russia')
(166, 'Anne King', '0014 Jesse Courts', '+1-804-736-0028x01816', 'Chennai', 'India')
(167, 'Robert Patton', '698 Huff River', '467-973-2483', 'Adelaide', 'Australia')
(168, 'Stephanie Murphy', '5163 Richard Manors', '(293)383-3315', 'Sydney', 'Australia')
(169, 'Emily Lynch', '7635 Baker Corner', '001-982-371-0062x02369', 'Dubai', 'Middle East')
(170, 'Marissa Daniel', '51724 Matthews Circle', '245-273-3980x76066', 'Madrid', 'Europe')
(171, 'Devin Wiggins', '550 Horn Court Apt. 697', '+1-842-430-4647x19020', 'Muscat', 'Middle East')
(172, 'Angel Tanner', '6133 James Stream', '490.562.3924', 'Novosibirsk', 'Russia')
(173, 'Justin Jones', '5353 Sanchez Lakes', '967.875.1440x30926', 'Delhi', 'India')
(174, 'Jenny Gonzalez', '0979 James Harbor', '001-564-442-4549x1093', 'Rome', 'Europe')
(175, 'Jacqueline Perry', '15046 Hoffman Mount Apt. 827', '(566)256-0649x2444', 'Moscow', 'Russia')
(176, 'Melissa Allen', '9128 Maldonado Flats', '(691)562-2480', 'Kolkata', 'India')
(177, 'Tyler Vaughn', '3745 Megan Junctions Apt. 316', '+1-823-576-3552x122', 'Kazan', 'Russia')
(178, 'Austin Herrera', '857 Delgado Plain', '963.753.6190x643', 'Melbourne', 'Australia')
(179, 'Jessica Flores', '7890 Christopher Drive Apt. 926', '(655)680-3673', 'Kazan', 'Russia')
(180, 'Brianna Martinez', '304 Wiley Road', '(859)425-6205x341', 'Sydney', 'Australia')
(181, 'Anita Smith', '2173 Espinoza Crest Suite 463', '(658)695-3601x9895', 'Adelaide', 'Australia')
(182, 'Stacy Vargas', '2903 Matthew Island', '+1-873-725-5261', 'Mumbai', 'India')
(183, 'Cindy Mcconnell', '7585 Kimberly Turnpike', '+1-329-318-7759x373', 'West Region', 'Singapore')
(184, 'Tony Lee', '84875 Cox Glen Apt. 228', '735.410.0968x57555', 'Central Region', 'Singapore')
(185, 'Kelli Rodriguez', '74464 Elizabeth Park Suite 140', '757.813.9940', 'Sydney', 'Australia')
(186, 'Micheal Knight', '523 Mary Valley', '463.565.9487x45467', 'Saint Petersburg', 'Russia')
(187, 'William Cox', '5334 Ann Village Apt. 767', '626-459-7782', 'Mumbai', 'India')
(188, 'Cynthia Smith', '63705 Donald Ville Apt. 911', '602.850.3505x67649', 'Brisbane', 'Australia')
(189, 'Deborah Price', '1921 Sampson Bridge Apt. 428', '609-336-8267x387', 'Delhi', 'India')
(190, 'Tara Ellis', '09995 Morton Trafficway Suite 777', '428.503.8765x8201', 'Muscat', 'Middle East')
(191, 'Joseph Robles', '4759 Alicia Club Apt. 913', '964.339.8829', 'West Region', 'Singapore')
(192, 'Rachel Arellano', '05482 Carrie Radial', '774-984-5947x7843', 'Berlin', 'Europe')
(193, 'William Bauer', '6741 Glenn Centers', '001-782-827-6072', 'Abu Dhabi', 'Middle East')
(194, 'Christopher Hunt', '3291 Jay Fall Suite 396', '(376)567-5805x071', 'Kolkata', 'India')
(195, 'Amanda Jackson', '6836 Michael Run', '466-579-4108x5782', 'Paris', 'Europe')
(196, 'Sandra Turner', '64255 Teresa Mountain', '657.342.5978x82797', 'Sydney', 'Australia')
(197, 'Cindy Brown', '573 Elliott Station', '(495)327-6316', 'Muscat', 'Middle East')
(198, 'Brittney Silva', '556 Jeffrey Spurs Suite 440', '670.244.0208', 'West Region', 'Singapore')
(199, 'Sarah Romero', '49972 Stein Extension', '544-354-4623', 'North Region', 'Singapore')
(200, 'Brandon Smith', '422 Everett Gardens', '(828)905-5735x624', 'Madrid', 'Europe')
(201, 'Courtney Sanchez', '288 Kevin Course Apt. 664', '+1-769-790-7847', 'Novosibirsk', 'Russia')
(202, 'Jose Sloan', '4884 David Park Suite 372', '2479298175', 'Sydney', 'Australia')
(203, 'David Harmon', '308 Lara Loaf', '2583054531', 'Moscow', 'Russia')
(204, 'Megan Patel', '6193 Russell Vista', '001-849-968-5705', 'Berlin', 'Europe')
(205, 'Natalie Baker', '42396 Baker Motorway', '698-413-8382', 'Kolkata', 'India')
(206, 'James Thompson', '959 Sarah Terrace Apt. 694', '+1-954-363-7072x1625', 'Perth', 'Australia')
(207, 'Lindsey Peters', '49120 Jeffrey Locks', '001-334-835-9608', 'Abu Dhabi', 'Middle East')

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [17]:
import csv
import os

# Specify the directory path
output_directory = "/content/drive/My Drive/raksha_pipes_csv"

# Create the directory if it doesn't exist
os.makedirs(output_directory, exist_ok=True)

# Save Products data to CSV


products_csv_path = os.path.join(output_directory, "products.csv")
with open(products_csv_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["product_id", "product_name", "price"])
    writer.writerows([(idx + 1, name, price) for idx, (name, price) in enumerate(product_names)])

# Rest of the code to save other tables' data to CSV

# Save Customers data to CSV
customers_csv_path = os.path.join(output_directory, "customers.csv")
with open(customers_csv_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["customer_id", "customer_name", "address", "phone_number", "state", "country"])
    writer.writerows(customers)

# Save Sales data to CSV
sales_csv_path = os.path.join(output_directory, "sales.csv")
with open(sales_csv_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["sale_id", "product_id", "customer_id", "quantity_sold", "sale_date"])
    writer.writerows(sales)

# Save Categories data to CSV
categories_csv_path = os.path.join(output_directory, "categories.csv")
with open(categories_csv_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["category_id", "category_name"])
    writer.writerows(categories)

# Save Orders data to CSV
orders_csv_path = os.path.join(output_directory, "orders.csv")
with open(orders_csv_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["order_id", "customer_id", "product_id", "payment_id", "order_date", "delivery_date"])
    writer.writerows(orders)

# Save Payments data to CSV
payments_csv_path = os.path.join(output_directory, "payments.csv")
with open(payments_csv_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["payment_id", "order_id", "amount", "payment_date"])
    writer.writerows(payments)

# Save Suppliers data to CSV
suppliers_csv_path = os.path.join(output_directory, "suppliers.csv")
with open(suppliers_csv_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["supplier_id", "company_name", "country"])
    writer.writerows(suppliers)

# Save Distributors data to CSV
distributors_csv_path = os.path.join(output_directory, "distributors.csv")
with open(distributors_csv_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["distributor_id", "company_name", "address", "phone_number", "country"])
    writer.writerows(distributors)

print("CSV files saved successfully.")

CSV files saved successfully.